apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sonarr
    repoURL: https://github.com/sandersch/homelab.git
    targetRevision: HEAD
