sonarr:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/issuer: "letsencrypt-staging"
      hosts:
      - host: sonarr.worm.run
        paths:
          - path: /
            pathType: Prefix
      tls:
      - secretName: sonarr-tls-certificate
        hosts:
        - sonarr.worm.run
  persistence:
    config:
      enabled: true
    media:
      enabled: true
      type: hostPath
      hostPath: /mnt/media
