sonarr:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
      - host: sonarr.worm.run
        paths:
          - path: /
            pathType: Prefix
      tls:
      - secretName: sonarr-tls-certificate
        hosts:
        - sonarr.worm.run
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
  persistence:
    config:
      enabled: true
      existingClaim: sonarr-config-zfs
    media:
      enabled: true
      type: hostPath
      hostPath: /mnt/media
    downloads:
      enabled: true
      type: hostPath
      hostPath: /mnt/downloads
      mountPath: /mnt/downloads
