kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-master-elasticsearch-master-2
spec:
  storageClassName: nvme0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
