apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: sawmill
spec:
  version: 8.5.2
  nodeSets:
  - name: sawmill
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: nvme0
