plex:
  image:
    tag: latest
  env:
    ADVERTISE_IP: 172.17.1.2
    NVIDIA_DRIVER_CAPABILITIES: all
  service:
    dnla-tcp:
      enabled: true
    dnla-udp:
      enabled: true
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
      - host: plex.worm.run
        paths:
          - path: /
            pathType: Prefix
      tls:
      - secretName: plex-tls-certificate
        hosts:
        - plex.worm.run
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
  resources:
    requests:
      cpu: 1
      memory: "1Gi"
    limits:
      nvidia.com/gpu: 1
  persistence:
    config:
      enabled: true
      existingClaim: plex-config
    media:
      enabled: true
      type: hostPath
      hostPath: /mnt/media
      mountPath: /data
