apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    namespace: platform
    server: https://kubernetes.default.svc
  project: default
  source:
    path: platform/kube-prometheus-stack
    repoURL: https://github.com/sandersch/homelab.git
    targetRevision: HEAD
