resources:
- ./all.yaml

patchesJson6902:
- target:
    group: apiextensions
    version: v1
    kind: CustomResourceDefinition
    name: prometheuses.monitoring.coreos.com
  path: ./use_replace_to_sync_prometheuses.yaml
