kube-prometheus-stack:
  alertmanager:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: "letsencrypt-staging"
      hosts:
      - alertmanager.worm.run
      tls:
      - secretName: alertmanager-general-tls
        hosts:
        - alertmanager.worm.run
  grafana:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: "letsencrypt-staging"
      hosts:
      - grafana.worm.run
      tls:
      - secretName: grafana-general-tls
        hosts:
        - grafana.worm.run
  prometheus:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: "letsencrypt-staging"
      hosts:
      - prometheus.worm.run
      tls:
      - secretName: prometheus-general-tls
        hosts:
        - prometheus.worm.run
