kube-prometheus-stack:
  alertmanager:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
      - alertmanager.worm.run
      tls:
      - secretName: alertmanager-general-tls
        hosts:
        - alertmanager.worm.run
  grafana:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
      - grafana.worm.run
      tls:
      - secretName: grafana-general-tls
        hosts:
        - grafana.worm.run
    additionalDataSources:
    - name: Loki
      type: loki
      url: http://monitoring-loki:3100
  prometheus:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
      - prometheus.worm.run
      tls:
      - secretName: prometheus-general-tls
        hosts:
        - prometheus.worm.run
loki-stack:
  loki:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
      - host: loki.worm.run
      tls:
      - secretName: loki-tls-certificate
        hosts:
        - loki.worm.run
