apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dragonfly-operator
namespace: dragonfly-operator
resources:
- https://raw.githubusercontent.com/dragonflydb/dragonfly-operator/v1.1.10/manifests/crd.yaml
- ns.yaml
