apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
spec:
  destination:
    namespace: helm-guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sabnzbd
    repoURL: https://github.com/sandersch/homelab.git
    targetRevision: HEAD
