sabnzbd:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
      - host: sabnzbd.worm.run
        paths:
          - path: /
            pathType: Prefix
      tls:
      - secretName: sabnzbd-tls-certificate
        hosts:
        - sabnzbd.worm.run
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
  persistence:
    config:
      enabled: true
      existingClaim: sabnzbd-config
    downloads:
      enabled: true
      type: hostPath
      hostPath: /mnt/downloads
      mountPath: /mnt/downloads
  additionalContainers:
    sabnzbd-exporter:
      image: msroest/sabnzbd_exporter:0.1.36
      ports:
      - containerPort: 9387
      env:
      - name: SABNZBD_BASEURL
        value: "http://localhost:8080"
      - name: SABNZBD_APIKEY
        valueFrom:
          secretKeyRef:
            name: sabnzbd-secrets
            key: api-key
