sabnzbd:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
      - host: sabnzbd.worm.run
        paths:
          - path: /
            pathType: Prefix
      tls:
      - secretName: sabnzbd-tls-certificate
        hosts:
        - sabnzbd.worm.run
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
  persistence:
    config:
      enabled: true
      setPermissions: true
    downloads:
      enabled: true
      type: hostPath
      hostPath: /mnt/downloads
      mountPath: /mnt/downloads
