apiVersion: v2
name: lumnis
version: 0.0.0
dependencies:
- name: logstash
  version: 8.5.1
  repository: https://helm.elastic.co
- name: elasticsearch
  version: 8.5.1
  repository: https://helm.elastic.co
