logstash:
  ingress:
    enabled: true
    className: public
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
       - host: logstash.worm.run
         paths:
           - path: /beats
             servicePort: 5044
           - path: /http
             servicePort: 8080
    tls:
    - secretName: logstash-tls-certificate
      hosts:
      - logstash.worm.run
  persistence:
    enabled: true
    storageClass: "nvme0"
elasticsearch:
  ingress:
    enabled: true
    className: public
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - host: elasticsearch.worm.run
        paths:
          - path: /
    tls:
    - secretName: elasticsearch-tls-certificate
      hosts:
      - elasticsearch.worm.run
  persistence:
    enabled: true
    storageClass: "nvme0"
  antiAffinity: "soft"
