logstash:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
       - host: logstash.worm.run
         paths:
           - path: /beats
             servicePort: 5044
           - path: /http
             servicePort: 8080
    tls:
    - secretName: logstash-tls-certificate
      hosts:
      - logstash.worm.run
  persistence:
    enabled: true
    storageClass: "nvme0"
    size: 25Gi
