kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-config
spec:
  storageClassName: nvme-mirror
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: "pvc-7537134c-4a4c-49ce-9ba0-e2d934384a4b"
