apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  labels:
    app.kubernetes.io/name: kapi
  annotations: 
    argocd.argoproj.io/sync-options: Replace=true
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kapi
    spec:
      containers:
      - command:
        - rails
        - db:migrate
        envFrom:
        - configMapRef:
            name: kapi
        - secretRef:
            name: kapi
        image: ghcr.io/sandersch/kapi:master
        imagePullPolicy: Always
        name: main
      restartPolicy: Never
