apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app.kubernetes.io/name: kapi
spec:
  storageClassName: nvme-mirror
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
