apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: postgres # Set the name of the deployment
  labels:
    app.kubernetes.io/name: kapi
spec:
  replicas: 1 # Set 1 deployment replicas
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine # Docker image
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: kapi
                  key: username.txt
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kapi
                  key: password.txt
                  optional: false
          ports:
            - containerPort: 5432 # Exposing the container port 5432 for PostgreSQL client connections.
          envFrom:
            - configMapRef:
                name: kapi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdat
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pvc
