apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: postgres # Set the name of the deployment
  labels:
    app.kubernetes.io/name: kapi
    process: postgres
spec:
  replicas: 1 # Set 1 deployment replicas
  selector:
    matchLabels:
      app.kubernetes.io/name: kapi
      process: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kapi
        process: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine # Docker image
          imagePullPolicy: "IfNotPresent"
          env:
          ports:
            - containerPort: 5432 # Exposing the container port 5432 for PostgreSQL client connections.
          envFrom:
            - configMapRef:
                name: kapi
            - secretRef:
                name: kapi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
