ingress-nginx:
  controller:
    ingressClassResource:
      name: public
      enabled: true
      default: true
    service:
      type: NodePort
      nodePorts:
        http: 32080
        https: 32443
