ingress-nginx:
  controller:
    ingressClassResource:
      name: public
      enabled: true
      default: true
    service:
      externalIPs: [172.17.1.2]
      type: NodePort
      nodePorts:
        http: 32080
        https: 32443
  tcp:
    32400: "plex/plex:32400"
