ingress-nginx:
  controller:
    ingressClassResource:
      name: public
      enabled: true
      default: true
    service:
      externalIPs: [172.17.1.2]
      type: NodePort
      nodePorts:
        http: 32080
        https: 32443
  tcp:
    3005: "plex/plex:3005"
    32469: "plex/plex:32469"
  udp:
    1900: "plex/plex:1900"
