
home-assistant:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: home-assistant.worm.run
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: home-assistant-tls-certificate
        hosts:
        - home-assistant.worm.run
  persistence:
    enabled: false
  configuration:
    trusted_proxies: 10.0.0.0/8
