---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd-exporter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd-exporter
  template:
    metadata:
      labels:
        app: sabnzbd-exporter
    spec:
      containers:
      - name: sabnzbd-exporter
        image: msroest/sabnzbd_exporter:0.1.36
        ports:
        - containerPort: 9387
        env:
        - name: SABNZBD_BASEURL
          value: "http://sabnzbd.sabnzbd.svc.cluster.local:8080"
        - name: SABNZBD_APIKEY
          valueFrom:
            secretKeyRef:
              name: sabnzbd-secrets
              key: api-key
