apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sawmill-kibana
  namespace: sawmill
spec:
  ingressClassName: public
  rules:
    - host: sawmill.worm.run
      http:
        paths:
          - backend:
              service:
                name: sawmill-kibana
                port:
                  number: 5601
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - samill.worm.run
      secretName: sawmill-kibana-tls-certificate
