apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sawmill-kibana
  namespace: sawmill
spec:
  rules:
    - host: sawmill.worm.run
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sawmill-kb-http
                port:
                  number: 5601
  tls:
    - hosts:
        - sawmill.worm.run
      secretName: sawmill-kibana-tls-certificate
